name: smart_sales
description: A new Flutter project.
publish_to: none
version: 2.0.0+3
environment:
  sdk: '>=2.17.0 <3.0.0'
dependencies:
  animated_splash_screen: ^1.1.0
  auto_size_text: ^3.0.0
  awesome_dialog: ^2.1.2
  badges: ^2.0.3
  bouncing_widget: ^2.0.0
  collection: ^1.15.0
  dio: ^4.0.4
  double_back_to_close: ^2.0.0
  dropdown_search: ^5.0.2
  easy_sidemenu: ^0.2.1
  encrypt: ^5.0.1
  expandable: ^5.0.1
  flutter:
    sdk: flutter
  flutter_animated_dialog: ^2.0.1
  flutter_barcode_scanner: ^2.0.0
  flutter_easyloading: ^3.0.5
  flutter_form_builder: ^7.2.1
  flutter_neumorphic: ^3.2.0
  flutter_speed_dial: ^5.0.0+1
  flutter_treeview: ^1.0.7+1
  font_awesome_flutter: ^10.1.0
  form_builder_validators: ^7.2.0
  geocoding: ^2.0.2
  geolocator: ^8.2.0
  get: ^4.6.1
  get_it: ^7.2.0
  get_storage: ^2.0.3
  google_fonts: ^2.1.1
  hawk_fab_menu: ^1.1.2
  internet_connection_checker: ^0.0.1+3
  intl: ^0.17.0
  path_provider: ^2.0.8
  pdf: ^3.6.0
  permission_handler: ^8.3.0
  platform_device_id: ^1.0.1
  printing: ^5.6.5
  provider: ^6.0.2
  qr_flutter: null
  responsive_framework: ^0.2.0
  retry: ^3.1.0
  screenshot: ^1.2.3
  settings_ui: ^2.0.2
  share_plus: ^4.0.4
  speed_dial_fab: ^2.1.1
  string_validator: ^0.3.0
  unique_identifier: ^0.2.2
  universal_io: ^2.0.4

dev_dependencies:
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - fonts/
    - assets/
  fonts:
    - family: Arabic
      fonts:
        - asset: fonts/arial.ttf
          weight: 700
